pipeline {
    agent any

    environment {
        IMAGE_NAME = "calculator"
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
        REGISTRY   = "calculator"
    }

    stages {
        stage('Build docker image') {
            steps {
                echo "docker"

                /* script {
                    docker.build("calculator:${env.IMAGE_TAG}")
                }*/
            }
        }
    }
}
