pipeline {
    agent any

    environment {
        BUILD_DIR = 'build'
    }

    stages {
        stage('Configure') {
            steps {
                echo "Configuring CMake..."
                script {
                    if (!fileExists(env.BUILD_DIR)) {
                        sh "mkdir -p ${env.BUILD_DIR}"
                    }
                    sh "cmake -S . -B ${env.BUILD_DIR}"
                }
            }
        }
        stage('Build') {
            steps {
                echo "building..."
                sh "cmake --build build"
            }
        }
        stage('Test') {
            steps {
                echo "testing..."
                sh "ctest --output-on-failure --test-dir ${env.BUILD_DIR}"
            }
        }
        stage('Deploy') {
            steps {
                echo "deploying..."
            }
        }
    }
}
